module.exports = {
  extends: ['stylelint-config-standard-scss'],
  ignoreFiles: [
    '**/node_modules/**',
    '**/dist/**',
    'output/**',
    'playwright-report/**',
    'test-results/**',
    'web/src/app/tokens.css',
    'website/styles/tokens.css',
    'mini/src/theme/tokens.scss',
  ],
  overrides: [
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss',
    },
  ],
  rules: {
    'alpha-value-notation': null,
    'at-rule-empty-line-before': null,
    'color-function-notation': null,
    'color-hex-length': null,
    'comment-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'custom-property-pattern': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-block-single-line-max-declarations': null,
    'declaration-empty-line-before': null,
    'font-family-no-missing-generic-family-keyword': null,
    'font-family-name-quotes': null,
    'function-url-quotes': null,
    'import-notation': null,
    'keyframes-name-pattern': null,
    'length-zero-no-unit': null,
    'media-feature-range-notation': null,
    'no-duplicate-selectors': null,
    'no-descending-specificity': null,
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': null,
    'shorthand-property-no-redundant-values': null,
    'unit-no-unknown': [true, { ignoreUnits: ['rpx'] }],
    'scss/at-import-partial-extension': null,
    'scss/dollar-variable-pattern': null,
    'scss/operator-no-unspaced': null,
    'selector-class-pattern': null,
    'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global', 'export'] }],
    'selector-type-no-unknown': [true, { ignoreTypes: ['page', 'navigator', 'scroll-view', 'swiper', 'checkbox'] }],
    'value-keyword-case': null,
    'value-no-vendor-prefix': null,
  },
};
