
export const DESIGNERS = [
    {
        id: 1,
        name: '张明远',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 8,
        rating: 4.9,
        reviewCount: 326,
        orgType: 'personal',
        orgLabel: '独立设计师',
        distance: '1.2km',
        specialty: '现代简约 · 北欧风格',
    },
    {
        id: 2,
        name: '李雅婷',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 12,
        rating: 4.8,
        reviewCount: 512,
        orgType: 'studio',
        orgLabel: '雅居设计工作室',
        distance: '2.5km',
        specialty: '新中式 · 轻奢风格',
    },
    {
        id: 3,
        name: '王建国',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 15,
        rating: 4.7,
        reviewCount: 892,
        orgType: 'company',
        orgLabel: '华美装饰设计公司',
        distance: '3.8km',
        specialty: '欧式古典 · 别墅大宅',
    },
    {
        id: 4,
        name: '陈思琪',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 5,
        rating: 4.9,
        reviewCount: 186,
        orgType: 'personal',
        orgLabel: '独立设计师',
        distance: '0.8km',
        specialty: '日式原木 · 极简主义',
    },
    {
        id: 5,
        name: '刘伟强',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 10,
        rating: 4.6,
        reviewCount: 445,
        orgType: 'studio',
        orgLabel: '强设计工作室',
        distance: '4.2km',
        specialty: '工业风 · Loft空间',
    },
    {
        id: 6,
        name: '周晓燕',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 7,
        rating: 4.8,
        reviewCount: 278,
        orgType: 'company',
        orgLabel: '燕归来设计公司',
        distance: '5.1km',
        specialty: '法式浪漫 · 田园风格',
    },
];

export const CONSTRUCTION_WORKERS = [
    {
        id: 1,
        type: 'personal',
        name: '老李师傅',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 20,
        rating: 4.9,
        reviewCount: 568,
        workTypes: ['mason', 'general'],
        workTypeLabels: '瓦工 · 综合施工',
        priceRange: '300-500',
        priceUnit: '元/天',
        completedOrders: 1256,
        distance: '1.5km',
        tags: ['手艺精湛', '准时守信', '价格公道'],
    },
    {
        id: 2,
        type: 'personal',
        name: '张电工',
        avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 15,
        rating: 4.8,
        reviewCount: 423,
        workTypes: ['electrician'],
        workTypeLabels: '电工',
        priceRange: '350-600',
        priceUnit: '元/天',
        completedOrders: 892,
        distance: '2.3km',
        tags: ['持证上岗', '安全第一', '经验丰富'],
    },
    {
        id: 3,
        type: 'company',
        name: '匠心装修工程有限公司',
        logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?q=80&w=200&auto=format&fit=crop',
        establishedYear: 2010,
        rating: 4.7,
        reviewCount: 1256,
        workTypes: ['mason', 'electrician', 'carpenter', 'painter', 'plumber'],
        workTypeLabels: '全工种覆盖',
        priceRange: '8-15',
        priceUnit: '万/全包',
        completedOrders: 3568,
        teamSize: 45,
        certifications: ['建筑装饰二级资质', 'ISO9001认证'],
        distance: '3.2km',
        tags: ['正规资质', '售后保障', '一站式服务'],
    },
    {
        id: 4,
        type: 'personal',
        name: '王木匠',
        avatar: 'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 25,
        rating: 4.9,
        reviewCount: 312,
        workTypes: ['carpenter'],
        workTypeLabels: '木工',
        priceRange: '400-700',
        priceUnit: '元/天',
        completedOrders: 756,
        distance: '4.1km',
        tags: ['老师傅', '传统手艺', '细节控'],
    },
    {
        id: 5,
        type: 'company',
        name: '鑫盛建筑装饰公司',
        logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?q=80&w=200&auto=format&fit=crop',
        establishedYear: 2015,
        rating: 4.6,
        reviewCount: 867,
        workTypes: ['mason', 'electrician', 'carpenter', 'painter'],
        workTypeLabels: '瓦/电/木/油',
        priceRange: '6-12',
        priceUnit: '万/全包',
        completedOrders: 2134,
        teamSize: 32,
        certifications: ['建筑装饰三级资质'],
        distance: '5.8km',
        tags: ['性价比高', '工期准时', '品质保障'],
    },
    {
        id: 6,
        type: 'personal',
        name: '刘师傅',
        avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 12,
        rating: 4.7,
        reviewCount: 245,
        workTypes: ['painter'],
        workTypeLabels: '油漆工',
        priceRange: '280-450',
        priceUnit: '元/天',
        completedOrders: 534,
        distance: '1.8km',
        tags: ['环保材料', '无异味', '细心负责'],
    },
];

export const MATERIALS = [
    {
        id: 1,
        name: '马可波罗瓷砖 现代简约灰色大理石',
        image: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?q=80&w=400&auto=format&fit=crop',
        brand: '马可波罗',
        category: 'tile',
        price: 89,
        originalPrice: 128,
        unit: '片',
        specs: '800x800mm',
        sales: 15680,
        rating: 4.9,
        reviewCount: 3256,
        tags: ['热销', '包邮'],
        shopName: '马可波罗官方旗舰店',
        isOfficial: true,
    },
    {
        id: 2,
        name: '圣象地板 E0级环保三层实木复合',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=400&auto=format&fit=crop',
        brand: '圣象',
        category: 'floor',
        price: 268,
        originalPrice: 358,
        unit: '㎡',
        specs: '1215x195x12mm',
        sales: 8956,
        rating: 4.8,
        reviewCount: 2134,
        tags: ['环保认证', '免费安装'],
        shopName: '圣象地板官方店',
        isOfficial: true,
    },
    {
        id: 3,
        name: 'TOTO智能马桶一体机 自动翻盖',
        image: 'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?q=80&w=400&auto=format&fit=crop',
        brand: 'TOTO',
        category: 'bathroom',
        price: 6999,
        originalPrice: 8999,
        unit: '套',
        specs: '智能款 CW887B',
        sales: 3256,
        rating: 4.9,
        reviewCount: 1856,
        tags: ['品牌直降', '送安装'],
        shopName: 'TOTO卫浴旗舰店',
        isOfficial: true,
    },
    {
        id: 4,
        name: '欧派整体橱柜 现代轻奢定制',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=400&auto=format&fit=crop',
        brand: '欧派',
        category: 'cabinet',
        price: 1999,
        originalPrice: 2599,
        unit: '延米',
        specs: '定制款',
        sales: 5623,
        rating: 4.7,
        reviewCount: 1523,
        tags: ['免费设计', '上门测量'],
        shopName: '欧派家居旗舰店',
        isOfficial: true,
    },
    {
        id: 5,
        name: 'TATA木门 现代简约室内门',
        image: 'https://images.unsplash.com/photo-1558618047-f4b511f5c6a3?q=80&w=400&auto=format&fit=crop',
        brand: 'TATA',
        category: 'door',
        price: 1580,
        originalPrice: 1980,
        unit: '樘',
        specs: '标准尺寸可定制',
        sales: 4521,
        rating: 4.8,
        reviewCount: 986,
        tags: ['静音门', '包安装'],
        shopName: 'TATA木门官方店',
        isOfficial: true,
    },
    {
        id: 6,
        name: '立邦乳胶漆 净味全效内墙面漆',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=400&auto=format&fit=crop',
        brand: '立邦',
        category: 'paint',
        price: 458,
        originalPrice: 598,
        unit: '桶/15L',
        specs: '白色 可调色',
        sales: 12356,
        rating: 4.9,
        reviewCount: 4523,
        tags: ['净味环保', '抗甲醛'],
        shopName: '立邦官方旗舰店',
        isOfficial: true,
    },
    {
        id: 7,
        name: '欧普照明 客厅吸顶灯LED',
        image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?q=80&w=400&auto=format&fit=crop',
        brand: '欧普',
        category: 'lighting',
        price: 899,
        originalPrice: 1299,
        unit: '套',
        specs: '三室两厅套餐',
        sales: 7865,
        rating: 4.8,
        reviewCount: 2365,
        tags: ['智能调光', '全屋套餐'],
        shopName: '欧普照明旗舰店',
        isOfficial: true,
    },
    {
        id: 8,
        name: '东鹏瓷砖 仿古砖客厅地砖',
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=400&auto=format&fit=crop',
        brand: '东鹏',
        category: 'tile',
        price: 68,
        originalPrice: 98,
        unit: '片',
        specs: '600x600mm',
        sales: 9856,
        rating: 4.7,
        reviewCount: 1896,
        tags: ['防滑耐磨', '送踢脚线'],
        shopName: '东鹏瓷砖专卖店',
        isOfficial: false,
    },
];
