
export const DESIGNERS = [
    {
        id: 1,
        name: '张明远',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 8,
        rating: 4.9,
        reviewCount: 326,
        orgType: 'personal',
        orgLabel: '独立设计师',
        distance: '1.2km',
        specialty: '现代简约 · 北欧风格',
        price: '¥120-300/㎡',
        serviceArea: ['雁塔区', '碑林区', '高新区'],
    },
    {
        id: 2,
        name: '李雅婷',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 12,
        rating: 4.8,
        reviewCount: 512,
        orgType: 'studio',
        orgLabel: '雅居设计工作室',
        distance: '2.5km',
        specialty: '新中式 · 轻奢风格',
        price: '¥200-400/㎡',
        serviceArea: ['未央区', '莲湖区', '经开区'],
    },
    {
        id: 3,
        name: '王建国',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 15,
        rating: 4.7,
        reviewCount: 892,
        orgType: 'company',
        orgLabel: '华美装饰设计公司',
        distance: '3.8km',
        specialty: '欧式古典 · 别墅大宅',
        price: '¥300-600/㎡',
        serviceArea: ['曲江新区', '雁塔区', '长安区'],
    },
    {
        id: 4,
        name: '陈思琪',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 5,
        rating: 4.9,
        reviewCount: 186,
        orgType: 'personal',
        orgLabel: '独立设计师',
        distance: '0.8km',
        specialty: '日式原木 · 极简主义',
        price: '¥150-350/㎡',
        serviceArea: ['碑林区', '新城区'],
    },
    {
        id: 5,
        name: '刘伟强',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 10,
        rating: 4.6,
        reviewCount: 445,
        orgType: 'studio',
        orgLabel: '强设计工作室',
        distance: '4.2km',
        specialty: '工业风 · Loft空间',
        price: '¥180-400/㎡',
        serviceArea: ['灞桥区', '浐灞生态区', '新城区'],
    },
    {
        id: 6,
        name: '周晓燕',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 7,
        rating: 4.8,
        reviewCount: 278,
        orgType: 'company',
        orgLabel: '燕归来设计公司',
        distance: '5.1km',
        specialty: '法式浪漫 · 田园风格',
        price: '¥250-500/㎡',
        serviceArea: ['雁塔区', '高新区', '未央区'],
    },
];

export const CONSTRUCTION_WORKERS = [
    {
        id: 1,
        type: 'personal',
        name: '老李师傅',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 20,
        rating: 4.9,
        reviewCount: 568,
        serviceLabel: '施工服务',
        priceRange: '300-500',
        priceUnit: '元/天',
        completedOrders: 1256,
        distance: '1.5km',
        tags: ['手艺精湛', '准时守信', '价格公道'],
    },
    {
        id: 2,
        type: 'personal',
        name: '张电工',
        avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 15,
        rating: 4.8,
        reviewCount: 423,
        serviceLabel: '施工服务',
        priceRange: '350-600',
        priceUnit: '元/天',
        completedOrders: 892,
        distance: '2.3km',
        tags: ['持证上岗', '安全第一', '经验丰富'],
    },
    {
        id: 3,
        type: 'company',
        name: '匠心装修工程有限公司',
        logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?q=80&w=200&auto=format&fit=crop',
        establishedYear: 2010,
        rating: 4.7,
        reviewCount: 1256,
        serviceLabel: '装修施工服务',
        priceRange: '8-15',
        priceUnit: '万/全包',
        completedOrders: 3568,
        teamSize: 45,
        certifications: ['建筑装饰二级资质', 'ISO9001认证'],
        distance: '3.2km',
        tags: ['正规资质', '售后保障', '一站式服务'],
    },
    {
        id: 4,
        type: 'personal',
        name: '王木匠',
        avatar: 'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 25,
        rating: 4.9,
        reviewCount: 312,
        serviceLabel: '施工服务',
        priceRange: '400-700',
        priceUnit: '元/天',
        completedOrders: 756,
        distance: '4.1km',
        tags: ['老师傅', '传统手艺', '细节控'],
    },
    {
        id: 5,
        type: 'company',
        name: '鑫盛建筑装饰公司',
        logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?q=80&w=200&auto=format&fit=crop',
        establishedYear: 2015,
        rating: 4.6,
        reviewCount: 867,
        serviceLabel: '装修施工服务',
        priceRange: '6-12',
        priceUnit: '万/全包',
        completedOrders: 2134,
        teamSize: 32,
        certifications: ['建筑装饰三级资质'],
        distance: '5.8km',
        tags: ['性价比高', '工期准时', '品质保障'],
    },
    {
        id: 6,
        type: 'personal',
        name: '刘师傅',
        avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?q=80&w=200&auto=format&fit=crop&face',
        yearsExperience: 12,
        rating: 4.7,
        reviewCount: 245,
        serviceLabel: '施工服务',
        priceRange: '280-450',
        priceUnit: '元/天',
        completedOrders: 534,
        distance: '1.8km',
        tags: ['环保材料', '无异味', '细心负责'],
    },
];

export const MATERIAL_SHOPS = [
    {
        id: 1,
        type: 'brand',
        name: '马可波罗瓷砖旗舰店',
        cover: 'https://images.unsplash.com/photo-1620626012761-d083460a9d0d?q=80&w=400&auto=format&fit=crop',
        brandLogo: 'https://via.placeholder.com/50x50?text=Marca',
        rating: 4.9,
        reviewCount: 328,
        mainProducts: ['大理石瓷砖', '岩板', '木纹砖'],
        productCategories: ['tile'],
        address: '红星美凯龙汶水店1楼A808',
        distance: '1.2km',
        openTime: '09:30-21:00',
        tags: ['免费停车', '设计服务', '送货上门'],
        isVerified: true,
    },
    {
        id: 2,
        type: 'showroom',
        name: '摩登建材综合展示中心',
        cover: 'https://images.unsplash.com/photo-1581141849291-1125c7b692b5?q=80&w=400&auto=format&fit=crop',
        rating: 4.7,
        reviewCount: 156,
        mainProducts: ['卫浴', '地板', '全屋定制'],
        productCategories: ['bathroom', 'floor', 'cabinet'],
        address: '宜山路建材一条街228号',
        distance: '3.5km',
        openTime: '09:00-18:00',
        tags: ['一站式购齐', '大牌集合'],
        isVerified: true,
    },
    {
        id: 3,
        type: 'brand',
        name: 'TOTO卫浴官方体验店',
        cover: 'https://images.unsplash.com/photo-1552321901-460eaee8a8cb?q=80&w=400&auto=format&fit=crop',
        brandLogo: 'https://via.placeholder.com/50x50?text=TOTO',
        rating: 4.8,
        reviewCount: 412,
        mainProducts: ['智能马桶', '花洒', '浴缸'],
        productCategories: ['bathroom'],
        address: '喜盈门国际建材品牌中心2楼',
        distance: '5.6km',
        openTime: '10:00-22:00',
        tags: ['新品体验', '预约安装'],
        isVerified: true,
    },
    {
        id: 4,
        type: 'showroom',
        name: '进口地板严选馆',
        cover: 'https://images.unsplash.com/photo-1622372738946-a287d377e81e?q=80&w=400&auto=format&fit=crop',
        rating: 4.6,
        reviewCount: 89,
        mainProducts: ['实木地板', '强化地板', '拼花地板'],
        productCategories: ['floor'],
        address: '凯旋路3500号',
        distance: '0.8km',
        openTime: '09:30-18:30',
        tags: ['进口品质', '环保认证'],
        isVerified: false,
    },
    {
        id: 5,
        type: 'brand',
        name: '欧派整家定制',
        cover: 'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?q=80&w=400&auto=format&fit=crop',
        brandLogo: 'https://via.placeholder.com/50x50?text=OPPEIN',
        rating: 4.8,
        reviewCount: 567,
        mainProducts: ['橱柜', '衣柜', '全屋定制'],
        productCategories: ['cabinet'],
        address: '江桥万达广场3楼',
        distance: '8.2km',
        openTime: '10:00-22:00',
        tags: ['免费量房', 'VR设计'],
        isVerified: true,
    },
];
