const windowConfig = {
  navigationBarBackgroundColor: '#FFFFFF',
  navigationBarTitleText: '家装平台',
  navigationBarTextStyle: 'black' as const,
  backgroundTextStyle: 'dark' as const,
  backgroundColor: '#F8F9FA',
};

export default {
  pages: [
    'pages/home/index',
    'pages/inspiration/index',
    'pages/inspiration/detail/index',
    'pages/inspiration/quote/index',
    'pages/cases/gallery/index',
    'pages/cases/detail/index',
    'pages/cases/scene-detail/index',
    'pages/reviews/index',
    'pages/progress/index',
    'pages/messages/index',
    'pages/profile/index',
    'pages/profile/edit/index',
    'pages/profile/favorites/index',
    'pages/providers/list/index',
    'pages/providers/company-album/index',
    'pages/providers/detail/index',
    'pages/material-shops/detail/index',
    'pages/booking/create/index',
    'pages/booking/list/index',
    'pages/booking/detail/index',
    'pages/proposals/list/index',
    'pages/proposals/detail/index',
    'pages/quote-tasks/detail/index',
    'pages/orders/pending/index',
    'pages/orders/list/index',
    'pages/orders/detail/index',
    'pages/orders/survey-deposit/index',
    'pages/payments/webview/index',
    'pages/projects/detail/index',
    'pages/projects/pause/index',
    'pages/projects/dispute/index',
    'pages/projects/bill/index',
    'pages/bookings/refund/index',
    'pages/refunds/list/index',
    'pages/chat/index',
    'pages/identity/apply/index',
    'pages/support/index',
    'pages/about/index',
    'pages/settings/index',
    'pages/settings/account-security/index',
    'pages/settings/account-security/change-phone/index',
    'pages/settings/account-security/change-password/index',
    'pages/settings/account-security/delete-account/index',
    'pages/settings/devices/index',
    'pages/settings/notification/index',
    'pages/settings/privacy/index',
    'pages/settings/general/index',
    'pages/settings/feedback/index',
    'pages/auth/login/index',
    'pages/auth/wechat-callback/index',
    'pages/auth/wechat-bind-phone/index',
    'pages/legal/user-agreement/index',
    'pages/legal/privacy-policy/index',
  ],

  tabBar: {
    custom: true,
    color: '#A1A1AA',
    selectedColor: '#111111',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tab/home.png',
        selectedIconPath: 'assets/tab/home-active.png',
      },
      {
        pagePath: 'pages/inspiration/index',
        text: '灵感',
        iconPath: 'assets/tab/inspiration.png',
        selectedIconPath: 'assets/tab/inspiration-active.png',
      },
      {
        pagePath: 'pages/progress/index',
        text: '进度',
        iconPath: 'assets/tab/progress.png',
        selectedIconPath: 'assets/tab/progress-active.png',
      },
      {
        pagePath: 'pages/messages/index',
        text: '通知',
        iconPath: 'assets/tab/message.png',
        selectedIconPath: 'assets/tab/message-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tab/profile.png',
        selectedIconPath: 'assets/tab/profile-active.png',
      },
    ],
  },

  window: windowConfig,
};
