//go:build ignore
// +build ignore

package main

import (
	"errors"
	"flag"
	"fmt"
	"home-decoration-server/internal/config"
	"home-decoration-server/internal/model"
	"home-decoration-server/internal/rbacsync"
	"home-decoration-server/internal/repository"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

type semver struct {
	major int
	minor int
	patch int
}

func main() {
	var (
		seedPath    = flag.String("seed", "scripts/seed_rbac_full.go", "seed script path")
		outputPath  = flag.String("output", "", "target migration sql path")
		skipDBCheck = flag.Bool("skip-db-check", false, "skip current sys_menus selector validation")
	)
	flag.Parse()

	catalog, err := rbacsync.LoadSeedMenuCatalog(*seedPath)
	if err != nil {
		failf("加载 seed 菜单目录失败: %v", err)
	}
	roleSelectors, err := rbacsync.ResolvePresetRoleSelectors(catalog)
	if err != nil {
		failf("解析预置角色模板失败: %v", err)
	}

	if !*skipDBCheck {
		cfg, err := config.Load()
		if err != nil {
			failf("加载配置失败: %v", err)
		}
		if err := repository.InitDB(&cfg.Database); err != nil {
			failf("数据库连接失败: %v", err)
		}
		menus, err := loadMenus()
		if err != nil {
			failf("读取 sys_menus 失败: %v", err)
		}
		if err := ensureSelectorsExistInMenus(roleSelectors, menus); err != nil {
			failf("模板与 sys_menus 不一致: %v", err)
		}
	}

	targetOutputPath := *outputPath
	if strings.TrimSpace(targetOutputPath) == "" {
		targetOutputPath, err = nextMigrationPath()
		if err != nil {
			failf("生成迁移文件名失败: %v", err)
		}
	}

	sqlContent := renderMigrationSQL(filepath.Base(targetOutputPath), roleSelectors)
	if err := os.MkdirAll(filepath.Dir(targetOutputPath), 0o755); err != nil {
		failf("创建迁移目录失败: %v", err)
	}
	if err := os.WriteFile(targetOutputPath, []byte(sqlContent), 0o644); err != nil {
		failf("写入迁移文件失败: %v", err)
	}

	if err := updateSnapshot(roleSelectors, catalog, filepath.Base(targetOutputPath)); err != nil {
		failf("更新 RBAC 快照失败: %v", err)
	}

	fmt.Printf("✅ 已生成 RBAC 预置角色补齐迁移: %s\n", targetOutputPath)
	fmt.Println("✅ 已更新快照: scripts/rbac/snapshot.json")
	fmt.Println("下一步：将新 migration 加入 deploy/scripts/lib/release_common.sh allowlist。")
}

func loadMenus() ([]model.SysMenu, error) {
	var menus []model.SysMenu
	if err := repository.DB.Find(&menus).Error; err != nil {
		return nil, err
	}
	return menus, nil
}

func ensureSelectorsExistInMenus(roleSelectors rbacsync.RoleSelectorMap, menus []model.SysMenu) error {
	pathIndex := map[string]int{}
	permissionIndex := map[string]int{}
	for _, menu := range menus {
		if path := strings.TrimSpace(menu.Path); path != "" {
			pathIndex[path]++
		}
		if permission := strings.TrimSpace(menu.Permission); permission != "" {
			permissionIndex[permission]++
		}
	}

	var missing []string
	for _, roleKey := range rbacsync.PresetRoleKeys() {
		for _, selector := range roleSelectors[roleKey] {
			switch selector.SelectorType() {
			case "path":
				if pathIndex[selector.SelectorValue()] == 0 {
					missing = append(missing, roleKey+"|path|"+selector.SelectorValue())
				}
			default:
				if permissionIndex[selector.SelectorValue()] == 0 {
					missing = append(missing, roleKey+"|permission|"+selector.SelectorValue())
				}
			}
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return fmt.Errorf("以下 selector 在 sys_menus 中不存在: %s", strings.Join(missing, ", "))
	}
	return nil
}

func renderMigrationSQL(migrationFile string, roleSelectors rbacsync.RoleSelectorMap) string {
	rows := buildSQLTemplateRows(roleSelectors)
	return fmt.Sprintf(`-- Auto-generated by scripts/rbac_reconcile_generate.go
-- Migration: %s
-- Strategy: preset roles auto-reconcile (insert missing only)

DO $$
DECLARE
    unresolved_count INTEGER := 0;
    unresolved_list TEXT := '';
BEGIN
    WITH template(role_key, selector_type, selector_value) AS (
        VALUES
%s
    ), unresolved AS (
        SELECT t.role_key, t.selector_type, t.selector_value
        FROM template t
        LEFT JOIN sys_menus m
               ON (t.selector_type = 'path' AND m.path = t.selector_value)
               OR (t.selector_type = 'permission' AND m.permission = t.selector_value)
        WHERE m.id IS NULL
    )
    SELECT COUNT(*), COALESCE(string_agg(role_key || ':' || selector_type || '=' || selector_value, E'\n'), '')
    INTO unresolved_count, unresolved_list
    FROM unresolved;

    IF unresolved_count > 0 THEN
        RAISE EXCEPTION 'RBAC reconcile aborted: selectors not found in sys_menus (%%): %%', unresolved_count, unresolved_list;
    END IF;
END $$;

WITH template(role_key, selector_type, selector_value) AS (
    VALUES
%s
), resolved_targets AS (
    SELECT DISTINCT r.id AS role_id, m.id AS menu_id
    FROM template t
    JOIN sys_roles r
      ON r.key = t.role_key
    JOIN sys_menus m
      ON (t.selector_type = 'path' AND m.path = t.selector_value)
      OR (t.selector_type = 'permission' AND m.permission = t.selector_value)
)
INSERT INTO sys_role_menus (role_id, menu_id)
SELECT rt.role_id, rt.menu_id
FROM resolved_targets rt
WHERE NOT EXISTS (
    SELECT 1
    FROM sys_role_menus existing
    WHERE existing.role_id = rt.role_id
      AND existing.menu_id = rt.menu_id
);
`, migrationFile, rows, rows)
}

func buildSQLTemplateRows(roleSelectors rbacsync.RoleSelectorMap) string {
	rows := []string{}
	for _, roleKey := range rbacsync.PresetRoleKeys() {
		for _, selector := range roleSelectors[roleKey] {
			rows = append(rows, fmt.Sprintf(
				"        ('%s', '%s', '%s')",
				escapeSQL(roleKey),
				escapeSQL(selector.SelectorType()),
				escapeSQL(selector.SelectorValue()),
			))
		}
	}
	return strings.Join(rows, ",\n")
}

func escapeSQL(value string) string {
	return strings.ReplaceAll(value, "'", "''")
}

func nextMigrationPath() (string, error) {
	entries, err := os.ReadDir("migrations")
	if err != nil {
		return "", fmt.Errorf("read migrations dir: %w", err)
	}

	versionPattern := regexp.MustCompile(`^v(\d+)\.(\d+)\.(\d+)_.*\.sql$`)
	maxVersion := semver{}
	found := false
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		matches := versionPattern.FindStringSubmatch(entry.Name())
		if len(matches) != 4 {
			continue
		}
		major, _ := strconv.Atoi(matches[1])
		minor, _ := strconv.Atoi(matches[2])
		patch, _ := strconv.Atoi(matches[3])
		current := semver{major: major, minor: minor, patch: patch}
		if !found || isVersionGreater(current, maxVersion) {
			maxVersion = current
			found = true
		}
	}
	if !found {
		return "", errors.New("no versioned migration files found")
	}
	next := semver{major: maxVersion.major, minor: maxVersion.minor, patch: maxVersion.patch + 1}
	filename := fmt.Sprintf("v%d.%d.%d_reconcile_preset_role_permissions.sql", next.major, next.minor, next.patch)
	return filepath.Join("migrations", filename), nil
}

func isVersionGreater(left semver, right semver) bool {
	if left.major != right.major {
		return left.major > right.major
	}
	if left.minor != right.minor {
		return left.minor > right.minor
	}
	return left.patch > right.patch
}

func updateSnapshot(roleSelectors rbacsync.RoleSelectorMap, catalog map[string]rbacsync.MenuSelector, migrationFile string) error {
	snapshotPath := filepath.Join("scripts", "rbac", "snapshot.json")
	catalogRows := rbacsync.BuildCatalogFingerprint(catalog)
	templateRows := rbacsync.BuildTemplateFingerprint(roleSelectors)

	snapshot := &rbacsync.Snapshot{
		SchemaVersion:          1,
		LastReconcileMigration: migrationFile,
		GeneratedAtUTC:         time.Now().UTC().Format(time.RFC3339),
		MenuCatalogHash:        rbacsync.HashStrings(catalogRows),
		TemplateHash:           rbacsync.HashStrings(templateRows),
		MenuCatalogRows:        catalogRows,
		TemplateRows:           templateRows,
		SelectorsByRole:        roleSelectors,
	}

	if previous, err := rbacsync.LoadSnapshot(snapshotPath); err == nil {
		switch {
		case previous.TemplateHash != snapshot.TemplateHash:
			snapshot.PreviousTemplateRows = previous.TemplateRows
		case len(previous.PreviousTemplateRows) > 0 && !equalStringSlices(previous.PreviousTemplateRows, snapshot.TemplateRows):
			snapshot.PreviousTemplateRows = previous.PreviousTemplateRows
		}
	}

	return rbacsync.SaveSnapshot(snapshotPath, snapshot)
}

func equalStringSlices(left []string, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i] != right[i] {
			return false
		}
	}
	return true
}

func failf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "❌ "+format+"\n", args...)
	os.Exit(1)
}
